"""Initial migration

Revision ID: 539134788bef
Revises: 
Create Date: 2025-06-27 08:22:03.099996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539134788bef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bandwidth_usage', schema=None) as batch_op:
        batch_op.create_index('idx_session_timestamp', ['session_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_timestamp_only', ['timestamp'], unique=False)
        batch_op.create_index('idx_username_timestamp', ['username', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_bandwidth_usage_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bandwidth_usage_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bandwidth_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bandwidth_usage_username'))
        batch_op.drop_index(batch_op.f('ix_bandwidth_usage_session_id'))
        batch_op.drop_index('idx_username_timestamp')
        batch_op.drop_index('idx_timestamp_only')
        batch_op.drop_index('idx_session_timestamp')

    # ### end Alembic commands ###
